name: live-dead-prediction
channels:
- defaults
dependencies:
    - python = 3.7
    - pip
    - pytest = 5.0.0
    - numpy
    - pandas
    - matplotlib = 3.1

    - pip:
      - setuptools
#      - -e grouped_control_prediction
#      - -e pysd2cat[harness]
      - -e src/grouped_control_prediction
      - -e src/pysd2cat[harness]
