name: fcs_signal_prediction
channels:
- defaults
dependencies:
    - python = 3.7
    - pip = 19.3.1
    - matplotlib = 3.1

    - pip:
      - flowcytometrytools
      - numpy
      - pandas
      - scikit-learn
#      - -e ../fcs_signal_prediction
#      - -e ../pysd2cat
      - -e ../src/fcs_signal_prediction
      - -e ../src/pysd2cat  # branch == 'development'