name: xplan-od-growth-analysis
channels:
- defaults
dependencies:
    - python = 3.7
    - pip
    - pytest = 5.0.0
    - numpy
    - pandas
    - pymongo
    - matplotlib = 3.1

    - pip:
      - pytest-html
      - pytest-timeout
      - flowcytometrytools
      - agavepy
      - xplan-od-growth-analysis
#      - /src/xplan-od-growth-analysis
